# .github/workflows/deploy.yml
name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # mainブランチにプッシュされたときに実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 依存関係をインストールする（frontendディレクトリで実行）
      - name: Install and Cache Dependencies
        run: npm install
        working-directory: frontend
        # 注: この方法ではキャッシュは使用しません。

      # Reactアプリケーションをビルドする
      - name: Make Vite executable
        run: chmod +x node_modules/.bin/vite
        working-directory: frontend
      - name: Build React App
        run: node_modules/.bin/vite build
        working-directory: frontend

      - name: Copy index.html to 404.html
        run: cp dist/index.html dist/404.html
        working-directory: frontend

      # GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 成果物があるディレクトリを指定
          publish_dir: ./frontend/dist 
          # サブディレクトリでのホストに対応
          # cname: syota9834.github.io/tbt003 # カスタムドメインではないためコメントアウト
